# Generated by Django 5.2.7 on 2025-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
